version: '3'

services:
  hzhong-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=hzhong
    # network_mode: REDE1
  hzhong-api:
    image: amandalfs/hzhong-node:prod
    ports:
      - 8020:8020
    # network_mode: REDE1

# volumes:
#   data-pg:
#     driver: local