version: '3'

services:
  hzhong-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=hzhong
  hzhong-api:
    image: amandalfs/hzhong-node:16
    ports:
      - 8020:8020